### ISSUE TITLE
[1.20.1] Server crash on join.

### ISSUE THREAD

**Issue by coldfusion818** [bigenergy/ftb-quests-optimizer#10]
When joining the server the client receives a connection reset error and the server crashes

FTBQuestsOptimizer-forge-2.0.0-1.20.1
ftb-library-forge-2001.2.1
ftb-quests-forge-2001.4.1
ftb-xmod-compat-forge-2.1.1
ftb-chunks-forge-2001.3.0
ftb-teams-forge-2001.3.0
ftb-filter-system-forge-2.0.1

Not sure if all of those mods are relevant but just incase.

[crash-2024-05-08_23.11.03-server.txt](https://github.com/bigenergy/ftb-quests-optimizer/files/15255897/crash-2024-05-08_23.11.03-server.txt)

**Comment by bigenergy** [comment]
@coldfusion818 thx for report, pls test new version
[FTBQuestsOptimizer-forge-2.0.1-1.20.1.zip](https://github.com/bigenergy/ftb-quests-optimizer/files/15255970/FTBQuestsOptimizer-forge-2.0.1-1.20.1.zip)

**Comment by coldfusion818** [comment]
@bigenergy I don't know what you did or how you did it that fast but I just tested it and it's fixed! thank you!
