### ISSUE TITLE
[1.20.1] Latest update (v2.0.1) makes quest detection very long, almost doesn't get completed until minutes later sometimes.

### ISSUE THREAD

**Issue by Gbergz** [bigenergy/ftb-quests-optimizer#11]
Latest update (v2.0.1) makes quest detection very long, almost doesn't get completed until minutes 45+ seconds and even later sometimes, (minutes).

Shuffling the required item in inventory does make it detect faster it seems. But it never detects item on first try. Anyhow. Something weird going on with latest version.

Rolling back to version 1.2.3 solves this issue, and its the version I'll be staying on for now.

**Versions:**
Forge: 47.2.17
FTB Quests: 2001.4.4
FTB Quests Optimizer: 2.0.1

(Modpack: TNP Limitless 7)

**Comment by bigenergy** [comment]
try the new version(2.0.2), I added a config to configure it
