### ISSUE TITLE
[1.16.5] Crash upon loading world

### ISSUE THREAD

**Issue by ReeCodes** [bigenergy/ftb-quests-optimizer#12]
Latest Log:
https://mclo.gs/ngxdhXL

How to achieve:
Have FTBQuestsOptimizer-1.16.5-1.0.0 installed and load into a world.

**Comment by Deepfriedyag** [comment]
I have the same problem. crash log --- https://pastebin.com/tiWgdUS7

**Comment by bigenergy** [comment]
for legacy versions ---> https://github.com/bigenergy/ftb-quests-optimizer-legacy/issues
