### ISSUE TITLE
Crash with the Latest version of the mod

### ISSUE THREAD

**Issue by Leclowndu93150** [bigenergy/ftb-quests-optimizer#3]
[latest.log](https://github.com/bigenergy/ftb-quests-optimizer/files/12640687/latest.log)
![image](https://github.com/bigenergy/ftb-quests-optimizer/assets/73310949/908af4c5-bcf1-4240-b5c7-be649594d39d)
it somehow blames GregTech but it has nothing to do with it

**Comment by Gbergz** [comment]
Can confirm, only using FTB Quests + Optimizer mod & the required addons.
Logs: https://gist.github.com/Gbergz/da9ec4a636f9c66608c20bf1e1715ab6

**Comment by Daltaxy** [comment]
interestingly, it also makes the mod Artifacts crash at launch
something about a missing item: night vision goggles

**Comment by Gbergz** [comment]
Nah that's just a fake error. Real error is the one I posted above.

**Comment by bigenergy** [comment]
thanks for the report, I'll check and fix it today

**Comment by bigenergy** [comment]
@TexBlock related to your pull request?

**Comment by TexBlock** [comment]
> @TexBlock related to your pull request?

yes，Maybe we'll have to mixin both the forge and fabric side all over again?

**Comment by bigenergy** [comment]
@Gbergz pls check this version
[FTBQuestsOptimizer-forge-1.1.1-1.20.1.zip](https://github.com/bigenergy/ftb-quests-optimizer/files/12641695/FTBQuestsOptimizer-forge-1.1.1-1.20.1.zip)

**Comment by bigenergy** [comment]
But I still couldn’t reproduce the problem with the same list of mods, tell me the details, do you install the mod on the server or client?

**Comment by Gbergz** [comment]
@bigenergy That version you posted above works.

**Comment by bigenergy** [comment]
> @bigenergy That version you posted above works.

Thank you, I uploaded the corrected version to curseforge
