### ISSUE TITLE
Mod is crashing on 1.19.2 Server using Latest version

### ISSUE THREAD

**Issue by ModernGamingWorld** [bigenergy/ftb-quests-optimizer#4]
[crash-2023-09-19_00.21.19-fml.txt](https://github.com/bigenergy/ftb-quests-optimizer/files/12656147/crash-2023-09-19_00.21.19-fml.txt)

**Comment by bigenergy** [comment]
please attach debug.log

**Comment by DexxKnight1** [comment]
[debug.log](https://github.com/bigenergy/ftb-quests-optimizer/files/12658595/debug.log)
I got the same server crush

**Comment by bigenergy** [comment]
[FTBQuestsOptimizer-forge-1.1.1-1.19.2.zip](https://github.com/bigenergy/ftb-quests-optimizer/files/12658766/FTBQuestsOptimizer-forge-1.1.1-1.19.2.zip)
@DexxKnight1 @ModernGamingWorld pls check this version

**Comment by bigenergy** [comment]
> This version works perfectly fine.

Thank you, I uploaded the fixed version to curseforge
