### ISSUE TITLE
[1.18.2]Crash When Statup

### ISSUE THREAD

**Issue by OcrSu** [bigenergy/ftb-quests-optimizer#5]
Mod File FTBQuestsOptimizer-forge-1.1.1-1.18.2.jar needs language provider javafml:43 or above to load
Java:17
OS:Win10
Crash Log:https://gist.github.com/OcrSu/144dac166ecb4f8081e0bf508f44d723

**Comment by bigenergy** [comment]
thx for report, this bug fixed in 1.1.2 version
