### ISSUE TITLE
Crash at world load

### ISSUE THREAD

**Issue by DelviousCrafts** [bigenergy/ftb-quests-optimizer#8]
The game crashes on world load with the latest version (1.2.1) of Optimizer. (also, as a side note, the fabric version of 1.2.1 seems to be available for forge installations on curseforge, but does not load obviously.)

Logs: 
- [Crash Report](https://gist.github.com/DelviousCrafts/f238cfa9ed601673ff46422ca0815c7d)
- [Latest Log](https://gist.github.com/DelviousCrafts/5e5129b80cbd5d02f28a492a7eba6465)
- [Debug Log](https://gist.github.com/DelviousCrafts/ed5cb658413e57943f8fa8771f8b060d)

Versions: 
- Minecraft: 1.20.1
- Forge: 47.2.20
- Architectury: 9.2.14
- FTB Library: 2001.1.5
- FTB Quests: 2001.3.4
- FTB Teams: 2001.2.0
- FTB Quests Optimizer: 1.2.1

**Comment by Leclowndu93150** [comment]
yep same issue

**Comment by bigenergy** [comment]
fixed in 1.2.2, thanks for report
