### ISSUE TITLE
[1.16.5] Crash when installing and entering a world

### ISSUE THREAD

**Issue by MundM2007** [bigenergy/ftb-quests-optimizer#9]
**Describe the Crash**
The game crashes when trying to enter any world

**To Reproduce**
1. create a profile with this mod and ftbquests
2. start the game
3. enter or create a world
4. See mixin error

**Versions (please complete the following information):**
- FTB Quest Optimizer version: FTBQuestsOptimizer-1.16.5-1.0.0.jar
- FTB Quests version: ftb-quests-forge-1605.3.7-build.165.jar
- other dependency mods are also on the newest version

**Crash Report / log**
[crash-2024-04-28_19.30.09-server.txt](https://github.com/bigenergy/ftb-quests-optimizer/files/15143018/crash-2024-04-28_19.30.09-server.txt)
[latest.log](https://github.com/bigenergy/ftb-quests-optimizer/files/15143019/latest.log)
[debug.log](https://github.com/bigenergy/ftb-quests-optimizer/files/15143020/debug.log)

**Comment by MundM2007** [comment]
Oh this is the wrong repo, should I open another in the lagacy one?

**Comment by bigenergy** [comment]
The mod is not needed on the client, basic optimizations are used only on a dedicated server.
Judging by the logs, you are using a mod on the client.

**Comment by MundM2007** [comment]
Ok,  I'm using it in a Client. So Singleplayer worlds aren't affected by those optimization problems?

**Comment by bigenergy** [comment]
> Ok, I'm using it in a Client. So Singleplayer worlds aren't affected by those optimization problems?

Actually no, problems arise when there are 5 or more players.

**Comment by MundM2007** [comment]
Ah, ok. Thanks for the explanation. Your second Mod is for both sides though?

**Comment by bigenergy** [comment]
> Ah, ok. Thanks for the explanation. Your second Mod is for both sides though?

how convenient, mostly on the server
